export enum SubCategoryEnum {
  // FE
  BROWSER = 'BROWSER',
  REACT = 'REACT',
  NEXT = 'NEXT',
  HTML = 'HTML',
  CSS = 'CSS',
  FE_ETC = 'FE_ETC',

  // BE
  OS = 'OS',
  DB = 'DB',
  NODE = 'NODE',
  SPRING = 'SPRING',
  BE_ETC = 'BE_ETC',

  // COMMON
  NETWORK = 'NETWORK',
  DATA_STRUCTURE = 'DATA_STRUCTURE',
  ALGORITHM = 'ALGORITHM',
  WEB = 'WEB',
  FIT = 'FIT',
  COMMON_ETC = 'COMMON_ETC',

  // LANGUAGE
  JAVASCRIPT = 'JAVASCRIPT',
  TYPESCRIPT = 'TYPESCRIPT',
  JAVA = 'JAVA',
}
